# This is a basic workflow to help you get started with Actions

name: Download new CSV file

# Controls when the workflow will run
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '00 10 * * *'


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  download:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: create input directory
        run: mkdir -p ./data/input
        
      - name: download file
        run: wget https://www.mise.gov.it/images/exportCSV/anagrafica_impianti_attivi.csv -O ./data/input/anagrafica_impianti_attivi.csv

      - name: create output directory
        run: mkdir -p ./data/output

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          awk -F';' 'BEGIN{OFS=";"; print "ref:mise;name;operator;address;latitude;longitude"} NR>=3 && NF == 10 && $8 ~ /^(CH|PE|AQ|TE)$/{print $1,$5,$2,$6,$9,$10}' ./data/input/anagrafica_impianti_attivi.csv > ./data/output/abruzzo_impianti_attivi.csv
      # push changes to GITHUB
      - name: push changes
        run: |
          git config user.name "actionman"
          git add -A
          git commit -m "Latest data: $(date -Iminutes) (a total of $(tail -n+3 ./data/input/anagrafica_impianti_attivi.csv | wc -l) fuel stations)" || exit 0
          git push
