# This is a basic workflow to help you get started with Actions

name: Download CSV file and update repository CSV files

# Controls when the workflow will run
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '00 10 * * *'


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: create input directory
        run: mkdir -p ./data/input
        
      - name: download CSV file from MISE
        run: |
          wget -q https://www.mise.gov.it/images/exportCSV/anagrafica_impianti_attivi.csv -O ./data/input/anagrafica_impianti_attivi.csv
          wget -q https://www.mise.gov.it/images/exportCSV/prezzo_alle_8.csv -O ./data/input/prezzo_alle_8.csv
        
      - name: create output directories
        run: |
          mkdir -p ./data/output/Abruzzo
          mkdir -p ./data/output/Toscana

      # Runs a set of commands using the runners shell
      - name: Update Abruzzo files
        run: |
          awk -F';' 'BEGIN{OFS=";"; print "ref:mise;name;operator;address;latitude;longitude"} {sub(/ +/,"",$9);sub(/ +/,"",$10)} NR>=3 && NF == 10 && $8 ~ /^(CH|PE|AQ|TE)$/ && $9 ~ /^[0-9]+\.[0-9]+$/ && $10 ~ /^[0-9]+\.[0-9]+$/{print $1,$5,$2,$6,$9,$10}' ./data/input/anagrafica_impianti_attivi.csv > ./data/output/Abruzzo/abruzzo_impianti_attivi.csv
          awk -F';' 'BEGIN{OFS=";"; print "ref:mise;name;operator;address;latitude;longitude"} {sub(/ +/,"",$9);sub(/ +/,"",$10)} NR>=3 && NF == 10 && $8 ~ /^(CH|PE|AQ|TE)$/ && ( $9 ~ /[^0-9.]/ || $10 ~ /[^0-9.]$/ ) {print $1,$5,$2,$6,$9,$10}' ./data/input/anagrafica_impianti_attivi.csv > ./data/output/Abruzzo/abruzzo_impianti_skipped.csv

      - name: Update Toscana files
        run: |
          awk -F';' 'BEGIN{OFS=";"; print "ref:mise;name;operator;address;latitude;longitude"} {sub(/ +/,"",$9);sub(/ +/,"",$10)} NR>=3 && NF == 10 && $8 ~ /^(AR|FI|GR|LI|LU|MS|PI|PO|PT|SI)$/ && $9 ~ /^[0-9]+\.[0-9]+$/ && $10 ~ /^[0-9]+\.[0-9]+$/{print $1,$5,$2,$6,$9,$10}' ./data/input/anagrafica_impianti_attivi.csv > ./data/output/Toscana/toscana_impianti_attivi.csv
          awk -F';' 'BEGIN{OFS=";"; print "ref:mise;name;operator;address;latitude;longitude"} {sub(/ +/,"",$9);sub(/ +/,"",$10)} NR>=3 && NF == 10 && $8 ~ /^(AR|FI|GR|LI|LU|MS|PI|PO|PT|SI)$/ && ( $9 ~ /[^0-9.]/ || $10 ~ /[^0-9.]$/ ) {print $1,$5,$2,$6,$9,$10}' ./data/input/anagrafica_impianti_attivi.csv > ./data/output/Toscana/toscana_impianti_skipped.csv

      # push changes to GITHUB
      - name: push changes
        run: |
          git config user.name "actionman"
          git add -A
          git commit -m "Latest data: $(date -Iminutes) (a total of $(tail -n+3 ./data/input/anagrafica_impianti_attivi.csv | wc -l) fuel stations)" || exit 0
          git push
